/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.seguradora.view;

/**
 *
 * @author Jon
 */
public class FrmAutomovel extends javax.swing.JFrame {

    /**
     * Creates new form FrmAutomovel
     */
    public FrmAutomovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCadastrarOcorrencia = new javax.swing.JButton();
        jBPesquisarOcorrencia = new javax.swing.JButton();
        jBEditarOcorrencia = new javax.swing.JButton();
        jBExcluirOcorrencia = new javax.swing.JButton();
        jBImprimirCliente = new javax.swing.JButton();
        jFDataOcorrencia = new javax.swing.JFormattedTextField();
        jTCodigoAutomovel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLAutomovel = new javax.swing.JLabel();
        jLCodOcorrencia = new javax.swing.JLabel();
        jLPlaca = new javax.swing.JLabel();
        jLFabricante = new javax.swing.JLabel();
        jLModelo = new javax.swing.JLabel();
        jLAnoModelo = new javax.swing.JLabel();
        jLAnoFabricante = new javax.swing.JLabel();
        jTLocalOcorrencia1 = new javax.swing.JTextField();
        jTLocalOcorrencia2 = new javax.swing.JTextField();
        jFAnoFabricante = new javax.swing.JFormattedTextField();
        jFAnoModelo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCadastrarOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-adicionar-marcador-48.png"))); // NOI18N
        jBCadastrarOcorrencia.setText("Cadastrar");
        jBCadastrarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarOcorrenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jBCadastrarOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, 70));

        jBPesquisarOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-search-48.png"))); // NOI18N
        jBPesquisarOcorrencia.setText("Pesquisar");
        jBPesquisarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarOcorrenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jBPesquisarOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 140, 70));

        jBEditarOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-update-48.png"))); // NOI18N
        jBEditarOcorrencia.setText("Editar");
        jBEditarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarOcorrenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jBEditarOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 140, 70));

        jBExcluirOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-delete-bookmark-48.png"))); // NOI18N
        jBExcluirOcorrencia.setText("Excluir");
        jBExcluirOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirOcorrenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jBExcluirOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 140, 70));

        jBImprimirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/printer.png"))); // NOI18N
        jBImprimirCliente.setText("Imprimir");
        jBImprimirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jBImprimirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 140, 70));
        getContentPane().add(jFDataOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, 25));
        getContentPane().add(jTCodigoAutomovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/projeto/userPesquisar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 70, 50));

        jLAutomovel.setFont(new java.awt.Font("Stylus BT", 0, 36)); // NOI18N
        jLAutomovel.setText("Automovel");
        getContentPane().add(jLAutomovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLCodOcorrencia.setText("Renavam:");
        getContentPane().add(jLCodOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 25));

        jLPlaca.setText("Placa:");
        getContentPane().add(jLPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 25));

        jLFabricante.setText("Fabricante: ");
        getContentPane().add(jLFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 25));

        jLModelo.setText("Modelo: ");
        getContentPane().add(jLModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, 25));

        jLAnoModelo.setText("Ano Modelo:");
        getContentPane().add(jLAnoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, 25));

        jLAnoFabricante.setText("Ano Fabricante:");
        getContentPane().add(jLAnoFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, 25));
        getContentPane().add(jTLocalOcorrencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, 25));
        getContentPane().add(jTLocalOcorrencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, 25));

        try {
            jFAnoFabricante.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFAnoFabricante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFAnoFabricante.setToolTipText("");
        getContentPane().add(jFAnoFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, 25));

        try {
            jFAnoModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFAnoModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFAnoModelo.setToolTipText("");
        getContentPane().add(jFAnoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 110, 25));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarOcorrenciaActionPerformed

    }//GEN-LAST:event_jBCadastrarOcorrenciaActionPerformed

    private void jBPesquisarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarOcorrenciaActionPerformed

    }//GEN-LAST:event_jBPesquisarOcorrenciaActionPerformed

    private void jBEditarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarOcorrenciaActionPerformed

    }//GEN-LAST:event_jBEditarOcorrenciaActionPerformed

    private void jBExcluirOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirOcorrenciaActionPerformed

    }//GEN-LAST:event_jBExcluirOcorrenciaActionPerformed

    private void jBImprimirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirClienteActionPerformed

    }//GEN-LAST:event_jBImprimirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAutomovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAutomovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarOcorrencia;
    private javax.swing.JButton jBEditarOcorrencia;
    private javax.swing.JButton jBExcluirOcorrencia;
    private javax.swing.JButton jBImprimirCliente;
    private javax.swing.JButton jBPesquisarOcorrencia;
    private javax.swing.JFormattedTextField jFAnoFabricante;
    private javax.swing.JFormattedTextField jFAnoModelo;
    private javax.swing.JFormattedTextField jFDataOcorrencia;
    private javax.swing.JLabel jLAnoFabricante;
    private javax.swing.JLabel jLAnoModelo;
    private javax.swing.JLabel jLAutomovel;
    private javax.swing.JLabel jLCodOcorrencia;
    private javax.swing.JLabel jLFabricante;
    private javax.swing.JLabel jLModelo;
    private javax.swing.JLabel jLPlaca;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTCodigoAutomovel;
    private javax.swing.JTextField jTLocalOcorrencia1;
    private javax.swing.JTextField jTLocalOcorrencia2;
    // End of variables declaration//GEN-END:variables
}
