/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.seguradora.view;

/**
 *
 * @author Jon
 */
public class FrmCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNome = new javax.swing.JLabel();
        jLRg = new javax.swing.JLabel();
        jLCpf = new javax.swing.JLabel();
        jLLogradouro = new javax.swing.JLabel();
        jLNr = new javax.swing.JLabel();
        jLComplemento = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLUf = new javax.swing.JLabel();
        jLCep = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTRg = new javax.swing.JTextField();
        jTCpf = new javax.swing.JTextField();
        jTLogradouro = new javax.swing.JTextField();
        jTNr = new javax.swing.JTextField();
        jTComplemento = new javax.swing.JTextField();
        jTBairro = new javax.swing.JTextField();
        jTCidade = new javax.swing.JTextField();
        jTUf = new javax.swing.JTextField();
        jTCep = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBCadastrarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(450, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNome.setText("Nome:");
        getContentPane().add(jLNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 110, 25));

        jLRg.setText("RG: ");
        getContentPane().add(jLRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 25));

        jLCpf.setText("CPF:");
        getContentPane().add(jLCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 25));

        jLLogradouro.setText("Logradouro:");
        getContentPane().add(jLLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, 25));

        jLNr.setText("NR:");
        getContentPane().add(jLNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, 25));

        jLComplemento.setText("Complemento:");
        getContentPane().add(jLComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 110, 25));

        jLBairro.setText("Bairro:");
        getContentPane().add(jLBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 25));

        jLCidade.setText("Cidade:");
        getContentPane().add(jLCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 25));

        jLUf.setText("UF:");
        getContentPane().add(jLUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 25));

        jLCep.setText("CEP:");
        getContentPane().add(jLCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 110, 25));

        jLTelefone.setText("Telefone:");
        getContentPane().add(jLTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 110, 25));
        getContentPane().add(jTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, 25));
        getContentPane().add(jTRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 25));
        getContentPane().add(jTCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, 25));
        getContentPane().add(jTLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 200, 25));
        getContentPane().add(jTNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 200, 25));
        getContentPane().add(jTComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, 25));
        getContentPane().add(jTBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, 25));
        getContentPane().add(jTCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, 25));
        getContentPane().add(jTUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 200, 25));
        getContentPane().add(jTCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 200, 25));
        getContentPane().add(jTTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 200, 25));

        jLabel1.setFont(new java.awt.Font("Stylus BT", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jBCadastrarCliente.setText("Cadastrar");
        getContentPane().add(jBCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 110, 25));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarCliente;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLCpf;
    private javax.swing.JLabel jLLogradouro;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNr;
    private javax.swing.JLabel jLRg;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JLabel jLUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCep;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTComplemento;
    private javax.swing.JTextField jTCpf;
    private javax.swing.JTextField jTLogradouro;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNr;
    private javax.swing.JTextField jTRg;
    private javax.swing.JTextField jTTelefone;
    private javax.swing.JTextField jTUf;
    // End of variables declaration//GEN-END:variables
}
