/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.seguradora.view;

import br.com.seguradora.controller.ControllerMenu;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jonatas.meireles
 */
public class FrmMenu extends javax.swing.JFrame {
    private final ControllerMenu controller;

    /**
     * Creates new form Tela02
     */
    public FrmMenu() {
        initComponents();
        controller =  new ControllerMenu(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopMenu = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCadastrarCliente = new javax.swing.JMenu();
        jMClienteAbrir = new javax.swing.JMenuItem();
        jMPesquisarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMAbrirAutomovel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMAbrirOcorrencia = new javax.swing.JMenuItem();
        jMRelatorios = new javax.swing.JMenu();
        jMAbrirRelatorios = new javax.swing.JMenuItem();
        jMSobre = new javax.swing.JMenu();
        jMAbrirSobre = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMAbrirAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seguradora de Automóveis - SENAI para Todos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 744));
        setName("frmMenu"); // NOI18N
        setResizable(false);

        jDesktopMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopMenu.setInheritsPopupMenu(true);
        jDesktopMenu.setMinimumSize(new java.awt.Dimension(1000, 590));
        jDesktopMenu.setName(""); // NOI18N
        jDesktopMenu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDesktopMenuComponentShown(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/img_fundo.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jDesktopMenu.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopMenuLayout = new javax.swing.GroupLayout(jDesktopMenu);
        jDesktopMenu.setLayout(jDesktopMenuLayout);
        jDesktopMenuLayout.setHorizontalGroup(
            jDesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopMenuLayout.setVerticalGroup(
            jDesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.getAccessibleContext().setAccessibleName("");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jMCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-myspace-48.png"))); // NOI18N
        jMCadastrarCliente.setText("Cliente");
        jMCadastrarCliente.setAutoscrolls(true);
        jMCadastrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMCadastrarCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMClienteAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMClienteAbrir.setText("Abrir");
        jMClienteAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMClienteAbrirActionPerformed(evt);
            }
        });
        jMCadastrarCliente.add(jMClienteAbrir);

        jMPesquisarCliente.setText("Teste de chamada de JInternalFrame");
        jMPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPesquisarClienteActionPerformed(evt);
            }
        });
        jMCadastrarCliente.add(jMPesquisarCliente);

        jMenuBar1.add(jMCadastrarCliente);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-traffic-jam-48.png"))); // NOI18N
        jMenu2.setText("Automóvel");
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMAbrirAutomovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMAbrirAutomovel.setText("Abrir");
        jMAbrirAutomovel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMAbrirAutomovelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMAbrirAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAbrirAutomovelActionPerformed(evt);
            }
        });
        jMenu2.add(jMAbrirAutomovel);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-privacy-policy-48.png"))); // NOI18N
        jMenu3.setText("Ocorrências");
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMAbrirOcorrencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMAbrirOcorrencia.setText("Abrir");
        jMAbrirOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAbrirOcorrenciaActionPerformed(evt);
            }
        });
        jMenu3.add(jMAbrirOcorrencia);

        jMenuBar1.add(jMenu3);

        jMRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-download-pie-chart-report-48.png"))); // NOI18N
        jMRelatorios.setText("Relatórios");
        jMRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMAbrirRelatorios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMAbrirRelatorios.setText("Abrir");
        jMRelatorios.add(jMAbrirRelatorios);

        jMenuBar1.add(jMRelatorios);

        jMSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-info-48.png"))); // NOI18N
        jMSobre.setText("Sobre");
        jMSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSobreActionPerformed(evt);
            }
        });

        jMAbrirSobre.setText("Abrir");
        jMAbrirSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAbrirSobreActionPerformed(evt);
            }
        });
        jMSobre.add(jMAbrirSobre);

        jMenuBar1.add(jMSobre);

        jMAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seguradora/imagens/icons8-help-48.png"))); // NOI18N
        jMAjuda.setText("Ajuda");
        jMAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMAjuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAjudaActionPerformed(evt);
            }
        });

        jMAbrirAjuda.setText("Abrir");
        jMAbrirAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAbrirAjudaActionPerformed(evt);
            }
        });
        jMAjuda.add(jMAbrirAjuda);

        jMenuBar1.add(jMAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMClienteAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMClienteAbrirActionPerformed
        // TODO add your handling code here:
        controller.Cliente();
    }//GEN-LAST:event_jMClienteAbrirActionPerformed

    private void jMSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSobreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMSobreActionPerformed

    private void jMAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAjudaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMAjudaActionPerformed

    private void jMPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPesquisarClienteActionPerformed
        try {
            // TODO add your handling code here:
            controller.PesquisarCliente();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMPesquisarClienteActionPerformed

    private void jMAbrirAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAbrirAjudaActionPerformed
        // TODO add your handling code here:
        this.controller.OpcaoMenuAjuda();
    }//GEN-LAST:event_jMAbrirAjudaActionPerformed

    private void jMAbrirSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAbrirSobreActionPerformed
        // TODO add your handling code here:
        this.controller.OpcaoMenuSobre();
    }//GEN-LAST:event_jMAbrirSobreActionPerformed

    private void jDesktopMenuComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopMenuComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopMenuComponentShown

    private void jMAbrirAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAbrirAutomovelActionPerformed
        // TODO add your handling code here:
        controller.Automovel();
        
    }//GEN-LAST:event_jMAbrirAutomovelActionPerformed

    private void jMAbrirAutomovelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMAbrirAutomovelAncestorAdded
         //TODO add your handling code here:
    }//GEN-LAST:event_jMAbrirAutomovelAncestorAdded

    private void jMAbrirOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAbrirOcorrenciaActionPerformed
        // TODO add your handling code here:
        controller.Ocorrencia();
    }//GEN-LAST:event_jMAbrirOcorrenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMAbrirAjuda;
    private javax.swing.JMenuItem jMAbrirAutomovel;
    private javax.swing.JMenuItem jMAbrirOcorrencia;
    private javax.swing.JMenuItem jMAbrirRelatorios;
    private javax.swing.JMenuItem jMAbrirSobre;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenu jMCadastrarCliente;
    private javax.swing.JMenuItem jMClienteAbrir;
    private javax.swing.JMenuItem jMPesquisarCliente;
    private javax.swing.JMenu jMRelatorios;
    private javax.swing.JMenu jMSobre;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
  
}
